### PR TITLE
[WIP] Add the manager UI

### PR DESCRIPTION
**Pull request by Senyoret1**
Changes:	
This PR adds the Skywire Manager‘s code, including the changes added in https://github.com/SkycoinProject/skywire/pull/1. The code was added in `static/skywire-manager-src/`, just like in https://github.com/SkycoinProject/skywire .

Apart from the code of the Skywire Manager, this PR only adds a `.gitignore` file in `static/skywire-manager-src/ssl ` for excluding the SSL tests certificates. The `.travis.yml` file was not changed, as there is nothing related to the manager in https://github.com/SkycoinProject/skywire/blob/master/.travis.yml.

How to test this PR:
You can find documentation in the readme file in the `static/skywire-manager-src/` folder

### CODE REVIEW

**Comment by Senyoret1** [comment]
The lastest commit includes modifications for making the manager work with the changes made in the mainnet-milestone2 branch. It also improves the process for creating and removing transports.

**Comment by Senyoret1** [comment]
The lastest commit makes the options related to the reoutes work, as it was working with hardcoded test data.

**Comment by Senyoret1** [comment]
The lastest commit adds some changes to the nodes list that were not correctly ported from the previous manager, so the manager can remember nodes for showing them offline and allow the user to change the label.

**Comment by Senyoret1** [comment]
The lastest commit adds several improvements to the apps list, to activate parts that were just showing test data, add options for starting/stopping the apps and a basic way to see the logs.

**Comment by Senyoret1** [comment]
The lastest commit adds options to let the user make operations to multiple transports/routes/app in the manager.

**Comment by Senyoret1** [comment]
The lastest commit includes some improvements:

- Make the elements on the list to always have the same order.

- Revert a test change that was made to the timer that refreshes the visor data.

- Show a message when the visor does not have apps.

- Change to the default labels.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:

- Now the procedure for updating the data periodically is more robust and react better in case of problems. The change also included a better separation of concerns.

- An option for selecting how often the data should be refreshed was added.

- A problem with the procedure for sorting the lists (added in the previous update) was fixed.

- Some unnecessary code was removed.

- Improvements for how some subscriptions are managed were added.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:

- Now the UI is shown in an adecuate state when loading data for populating a page for the first time, instead of showing empty controls or old/invalid data, hoping for the data to be loaded quickly.

- Now the UI shows more information about the automatic data update process and reacts better in case of errors. This included improving the “refresh” button.

- For being able to add the new loading indicators, the general UI containers used for most of the app were slightly improved. This solved a problem which made a horizontal scrollbar to always appear if the content was too tall.

**Comment by Senyoret1** [comment]
The last 2 commits include the following changes:

- Now the app gets more info from the hypervisor API.

- Now the bar at the right of the visor details page shows valid info, instead of test data. The design was also improved a bit.

- Small improvements were added to how the visors saved to persistent storage are managed.

- Now the tabs of the visor details page are at the top, not on the left bar.

- Small improvements to the layout.

**Comment by Senyoret1** [comment]
The last commits include the following changes:

- The upload/download charts were fixed, as the layout had several problems.

- Now the page with the details of the visors only shows some transports, routes and apps. If there are many elements, a link is shown to let the user go to a new page with the complete list and pagination controls, if needed.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:

- A new header control, for showing tabs, was created an added to the pages that needed it. It includes variaous UI/UX improvements over the design the manager had.

- Some hardcoded texts are now in the translation file.

-  Some bugs in the layout were fixed.

- The code for managing the labels of the visors was improved.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:

- Now the left bar does not have delays for showing the contents, so there are no more consistency problems while loading data.

- Some options of the left bar were changed, as it had some redundant options and options that were not really nedded.

- Some options that are still not implemented were deactivated, but not deleted.

- The component used to show buttons was modified, to show the icons correctly.

- The loading indicador is now shown under the tab bar, for a better UI/UX.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:

- A problem with the option for changing the labels was solved.

- The options for Angular to recycle the page components was deactivated, to avoid problems when the URLs are set by hand in the brwoser.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:

- A confirmation dialog was added to the app and is used to ask for confirmation before deleting elements and stopping apps.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:

- Several improvements for various modal windows, including code that responds better in case of errors, better UI feedback while loading data, UX improvements for the forms, general improvements for the code, fix problems with the scroll and more.

**Comment by Senyoret1** [comment]
The lastest commit includes small improvements for the UI of the manager.

**Comment by Senyoret1** [comment]
The last 2 commits include the following changes:

- Improvements for the transport list and the addition of a details window.

- Controls for filtering the app logs list by date.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:

- Adds a new snackbar which shows icons and has background colors, to allow the user quickly identify if the displayed message is an error, a warning or a confirmation.

- The app no longer uses the previous snackbar.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:

- Now the options on the left bar are activated almost instantly.

- Now the tab bar does not have a delay before allowing the user to change tabs. 

- Now when a text is truncated, a tooltip allows the user to see the full text.

- Small change to the title of the terminal window.

- A problem with the duration of the snackbar was fixed.

**Comment by Senyoret1** [comment]
The last 2 commits include the following changes:

- Now, if the browser window is too small, the app shows an alert covering all the UI. This is to avoid showing an inadecuate UI to the user, as the design is not responsive.

- Some improvements related to when to show and hide the snackbar were added.

**Comment by Senyoret1** [comment]
The last 2 commits include the following changes:

- Now it is possible to configure the initial account password from the manager.

- A small bug when checking the state of the apps was fixed.

- Now the UI reacts well if the visor details page is opened with invalid params.

- Multiple improvements for `PasswordComponent`.

- Now the modal windows are closed when the app navigates to another page.

- Other minor improvements.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:

- The script used in the desktop wallet for checking the state of the translation was added, including its documentation.

- Now the language config is managed in a centralized service.

- A modal window for selecting the language was added.

- The language options were removed from the settings form. There is now a small button for changing the language and it is always visible in the app’s header, but only if there is more than one language available.

- The layout of the header was improved a bit.

- In dev builds it is possible to select between English and Spanish. However, the Spanish option does nothing, it was added just for testing the UI, so it is not available in production builds.

The changes are based in the code for language management of the desktop wallet, but have several changes.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:

- Now it is possible to sort the lists by clicking in the header.

- Small improvements for the apps lists.

**Comment by evanlinjin** [comment]
@Senyoret1 can you reopen this PR to point to `SkycoinProject:master`? Thanks!

**Comment by Senyoret1** [comment]
@evanlinjin Done: https://github.com/SkycoinProject/skywire-mainnet/pull/59

**Pull request closed without merging**
